# Generated by Django 6.0.6 on 2026-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_spell_author_spell_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тэг')),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='spells', to='pages.tags', verbose_name='Тэг'),
        ),
    ]
