# Generated by Django 6.0.6 on 2026-06-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tags_spell_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
